DROP TABLE outbox_events CASCADE;
DROP TABLE agendamentos CASCADE;

CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_agendamentos_schedule_order CHECK (ends_at > scheduled_at)
);

CREATE INDEX idx_agendamentos_patient_id ON agendamentos (patient_id);
CREATE INDEX idx_agendamentos_scheduled_at ON agendamentos (scheduled_at);

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_outbox_pending ON outbox_events (status, next_attempt_at, created_at);

CREATE TABLE usuarios_novos (
    id BIGINT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_role VARCHAR(30) NOT NULL,
    CONSTRAINT uq_usuarios_novos_username UNIQUE (username),
    CONSTRAINT ck_usuarios_novos_role CHECK (user_role IN ('MEDICO', 'ENFERMEIRO', 'PACIENTE'))
);

INSERT INTO usuarios_novos (id, username, password_hash, user_role)
SELECT ROW_NUMBER() OVER (ORDER BY username), username, password_hash, user_role
FROM usuarios;

DROP TABLE usuarios;
ALTER TABLE usuarios_novos RENAME TO usuarios;